---

- hosts: all
  become: true
  tasks:

  - name: MISE à jour Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: MISE à jour Centos
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"      

- hosts: workstations
  become: true
  tasks:

  - name: installation unzip
    package:
      name: unzip
 
  - name: installation de terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


# Ici ces serveurs seront ciblés  
- hosts: web_serveurs
  become: true
  tasks:

  - name: instalation de apache et de php UBUNTU
    tags: apache,apache2,php,ubuntu,maria
    apt:
      name:
        - apache2
        - php7.0-cli
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: installation de httpd et php CENTOS
    tags: apache,apache2,centos,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Envoie de fichier sur le serveur html
    tags: html,site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
      
- hosts: db_serveurs
  become: true
  tasks:

  - name: installation de base de données mariadb Centos
    tags: apache,apache2,ubuntu,maria
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: installation de base de données mariadb Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_serveurs
  become: true
  tasks:

  - name: installation du serveur de fichier
    tags: samba
    package:
      name: samba
      state: latest
