---

- hosts: all
  become: true
  tasks:

  - name: Mise a jour du repository et instalation de apache et php
    package:
      name: 
        - "{{ variable_apache_paquet }}"
        - "{{ variable_php_paquet }}"
      update_cache: yes
      state: latest
