---

- hosts: all
  become: true
  tasks:

  - name: instalation de mise à jour update (Centos) 
    yum:
      name: 
      update_cache: yes
      when: ansible_distribution == "CentOS"

  - name: instakation mise à jour (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_serveurs
  become: true
  tasks:

  - name: instalation de apache  sur ubuntu serveur
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: instalation de apache  sur ubuntu serveur     
    dnf:       
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
