---

- hosts: all
  become: true
  tasks:

  - name: instalation de mise à jour (Centos) 
    package: 
      update_only: yes
      update_cache: yes
      when: ansible_distribution == "CentOS"

  - name: instalation de mise à jour (Ubuntu)
    package:
      upgrade: dist
      update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_serveurs
  become: true
  tasks:

  - name: instalation de apache  sur ubuntu serveur
    package:
      name:
        - apache2
        - php5-cli
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: instalation de apache  sur ubuntu serveur     
    package:       
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
